FROM node:18-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build
ENV PORT 4173
EXPOSE 4173
CMD ["node", "build"]

#FROM nginx:1.23.1-alpine
#COPY --from=build /app/src /usr/share/nginx/html
