version: '3'

volumes:
  postgres_data:
    driver: local
networks:
  static-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:

  front:
    image: frontend:v8
    restart: always
    ports:
      - 4173:4173
    environment:
      - url=https://timeflow.test.dyvenia.com
      - PUBLIC_SVELTEKIT_DEV_BASE_URL=http://localhost:8002
    networks:
      static-network:
        ipv4_address: 172.28.1.5 # Added frontend image to docker-compose file

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
    networks:
      static-network:
        ipv4_address: 172.28.1.3

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5435:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pguser@postgres.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      static-network:
        ipv4_address: 172.28.1.4

  fastapi:
    image: fastapi:v3
    volumes:
      - ./backend/:/backend/
      - ./requirements.txt/:/requirements.txt/
    command: >
      bash -c "export TIMEFLOW_DEV=true  && uvicorn backend.main:app --reload  --reload-dir ./backend --port 8002 --host 0.0.0.0"
    ports:
      - 8002:8002
    depends_on:
      - "db"
    container_name: fastapi
    stdin_open: true # docker run -i
    tty: true # docker run -t
    restart: on-failure
    networks:
      static-network:
        ipv4_address: 172.28.1.2

  postgres:
    container_name: postgres_blog
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
    networks:
      static-network:
        ipv4_address: 172.28.1.10
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    ports:
      - 5433:5432

  keycloak:
    container_name: keycloak_blog
    image: quay.io/keycloak/keycloak:19.0.3
    depends_on:
      - "postgres"
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_blog/postgres
      KC_DB_PORT: 5433
      KC_DB_USERNAME: pguser
      KC_DB_PASSWORD: password
    ports:
      - 8080:8080
    networks:
      static-network:
        ipv4_address: 172.28.1.11
