"""create supervisor column for appuser model

Revision ID: 96aab4402d14
Revises: 
Create Date: 2022-07-06 11:54:21.831120

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '96aab4402d14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appuser', sa.Column('supervisor', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='app_db')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appuser', 'supervisor', schema='app_db')
    # ### end Alembic commands ###
