"""add business day column

Revision ID: bd25fbcfe742
Revises: 
Create Date: 2022-07-06 15:05:24.945326

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bd25fbcfe742'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('business_day', sa.Boolean(), nullable=True), schema='app_db')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar', 'business_day', schema='app_db')
    # ### end Alembic commands ###
