"""Add start_date column to EpicArea model

Revision ID: b85bfd91b12d
Revises: 
Create Date: 2022-06-27 10:59:15.862647

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "b85bfd91b12d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "epicarea",
        sa.Column("start_date", sa.DateTime(), nullable=True),
        schema="app_db",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("epicarea", "start_date", schema="app_db")
    # ### end Alembic commands ###
